### PR TITLE
add PMDWin

### PR DESCRIPTION
**Pull request by jpcima**
@papiezak added PMDWin as emulator choice

I had it in store for a while but not completed..
I cleaned up some warnings.

I don't think this one does SSG-EG

### CODE REVIEW

**Comment by Wohlstand** [comment]
Also, I think, you need to correct the volume level, I think, it's too high from this PMDWin, I have tested that myself, and one of instrument have got clipped while I played chords...
And yeah, SSG-EG doesn't works on it :thinking:

**Comment by Wohlstand** [comment]
And, you have forgot to list it in benchmark (src/opl/measurer.cpp)

**Comment by jpcima** [comment]
Yes it has hearable clipping, I believed this happened internally. I will check.
I will add PMDWin to the benchmark.

**Comment by Wohlstand** [comment]
Wow, PMDWin has performance very closed to GENS :fox_face:

**Comment by jpcima** [comment]
Added soft panning.
Since the multiplication needed would have overflowed the `int32_t` channel value, I moved the volume reduction which prevents clipping to a place further up.

I have seem to have problems of sticky notes on this emulator, in realtime play, which do not reproduce when using MAME.

**Pull request merged**
