### PR TITLE
add basic MIDI

### PR DESCRIPTION
**Pull request by jpcima**
This adds the basic MIDI from OPL3BankEditor, except voice management.

**Please note:** I have not done a relayout of this UI, so it's still full of display glitches for me.
So, I've just dropped the MIDI input component in there, and I leave it to you to place it to your liking, according to your display.

### CODE REVIEW

**Comment by Wohlstand** [comment]
So, I only need to port the voice management, that is even simpler than on OPL2 as OPN2 has only 6 channels of one mode. The only possible different modes are: 5chans + 1DAC or special mode of 3'th channel when every operator of 3'th channel able to have own pitch value.

**Comment by Wohlstand** [comment]
One note about of voice management thing: it's super-easy to copy from OPL3 Bank Editor and you can keep it 1:1 same. The only use six channels only without of re-allocation as is in use only one mode of chip without of DAC and without of Ch3-Special mode yet.

**Comment by jpcima** [comment]
Hello ! I know nothing of OPN2 architecture but OK I will look.

**Comment by Wohlstand** [comment]
OPN2 is in some cases similar to OPL3, however has different registers and data to send, therefore I have pre-included the specification of the OPN2 chip if you want to understand it better. Yeah, On moment I first time created this editor and later libOPNMIDI I also knew nothing, but I have learned that and experimented with some stuff around and then I have understood it well :wink:

**Comment by Wohlstand** [comment]
For the case of voice management you don't need to contact the chip, you only need to replace mapper I have here with mine mapper from OPN2 Bank Editor

**Comment by jpcima** [comment]
A thing I have forgot to tell you: turns out ASIO compatibility goes as far back as windows 98. http://www.asio4all.org/
It's a thing I found at the moment I last reinstalled this thing on a Windows 8 for testing.
It might be that all audio backends can be enabled regardless of windows version.

**Comment by Wohlstand** [comment]
Windows 98 is minimal supported, Windows 95 I have tested long times ago and the stuff is not working on it, Win95 is too old for that. However, Win98 is most fine for OPL3 stuff and most DOS games are perfectly working with it and playing OPL3 music fine (same DOS games on WinNT working clunky and will never give OPL3 music even you are using valid sound card).

**Comment by jpcima** [comment]
Go tell to users of korg oasys pci that audio playback of windows 98 is perfectly fine :smile:

**Comment by jpcima** [comment]
In OPL3 `changePatch` the channel array gets allocated only in the `!isAdLibDrums` branch of the condition.
Is this a mistake?
https://github.com/Wohlstand/OPL3BankEditor/blob/master/src/opl/generator.cpp#L807

**Comment by Wohlstand** [comment]
For now Rythm-Mode percussions are don't using voice management, so that doesn't matter. The sense to use a voice management by rythm-mode percussions is in libADLMIDI where is need to play them. And, for now, there are incomplete: cymbals and hi-hats are not working on Nuked and on real chip, but working on DosBox and I looking for a reason why there are not wokring on Nuke/Real... When I'll complete them, I'll rework the whole support of rythm-mode in libADLMIDI as current implementation of rythm-mode drums is sucks: it's not works for the banks, but works for CMF/EAMUS only playback. I want to rework that to correctly use rythm-mode drums in banks too.

**Pull request merged**
