### PR TITLE
Deduplicate operator UI and simplify

### PR DESCRIPTION
**Pull request by jpcima**
This is an update of UI code to simplify for future development.
For now, I have not tried very extensively.

The operator UI, which is done 4 times in the main window, has been deduplicated into 1.
At the same time, all the duplicated slot handling was eliminated.

I took a simpler way of doing: read or write a whole operator from the control set.
The current way is not too different in logic, it's about equivalent except in smaller code size.

### CODE REVIEW

**Comment by Wohlstand** [comment]
I'll review this soon, loos good idea, I wanted to make same, but was focused on other things...

**Comment by jpcima** [comment]
Hi, did you have some time to review this patch?

**Comment by Wohlstand** [comment]
Oh, thanks for reminding, didn't review as I was overtired and often out of my home... Gonna check it...

**Comment by jpcima** [comment]
Yeah I really wish that I can port it over to OPL3-BE.
I've wanted this so I can implement easier copy-pasting betweem the operators.

**Comment by Wohlstand** [comment]
One thing I forgot - it conflicts with my experimental branch related to PSG and DACs, however, that's fine, that branch partially is crap, and I think, I'll rework it into something different...

**Comment by Wohlstand** [comment]
Merged this!
I also have made a small change to add translationing into operator widgets which was missing... Now everything works! :fox_face:

**Comment by Wohlstand** [comment]
~~Okay, bye bye my `sketch-psg-and-wt` branch, it's now broken, will remake it then, or will try to merge with this... Looks like only 3 files are conflicted, I hope, that shoud be easy to fix...~~

**Comment by jpcima** [comment]
Alright good, I will later repeat this work on OPL side. Thanks :+1:

**Pull request merged**
